## tomcat
server:
  port: 8089

##数据源
spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  application:
    name: nacos-server
  profiles:
    active: dev
  datasource:
    name: test01
    url: jdbc:mysql://localhost:3306/test01?useUnicode=true&characterEncoding=utf8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC #url
    username: root
    password: root3306
    driver-class-name: com.mysql.jdbc.Driver

  redis:
    #redis数据库，其有16个数据库
    database: 0
    #redis服务器地址
    host: localhost
    #redis服务器端口号
    port: 6379
    #连接池配置
    lettuce:
      pool:
        enabled: true
        max-active: 8
        max-wait: 10s

## mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.test.bean
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#   swagger
swagger:
  enabled: true